branch-defaults:
  master:
    environment: UNCACourseFinder-dev
global:
  application_name: UNCACourseFinder
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
